### ISSUE TITLE
Link to latest install.ps1 script is broken. Wheel is not supported on this platform

### ISSUE THREAD

**Issue by khakhilev** [nijave/borg-windows-package#4]
Hello! It looks like this solution is perfect for my needs, but I can't install it properly
1) When using suggested ps1 script link github returns 404
https://github.com/nijave/borg-windows-package/releases/download/latest/install.ps1
2) If I replace this link manually with latest or older versions (e.g. https://github.com/nijave/borg-windows-package/releases/download/cyg3.1.7-py3.8.8-borg1.1.16/install.ps1)
Setup runs fine till pip3 wheel installation command
pip3 install https://github.com/nijave/borg-windows-package/releases/download/cyg3.1.7-py3.8.8-borg1.1.15/borgbackup-1.1.15-cp38-cp38-cygwin_3_1_7_x86_64.whl borgmatic 

But fails with "ERROR: borgbackup-1.1.16-cp38-cp38-cygwin_3_1_7_x86_64.whl is not a supported wheel on this platform."

This is true to any other older script version I tried
I'm running script on fresh win10 202H x64 installation

**Comment by nijave** [comment]
>     1. When using suggested ps1 script link github returns 404
>        https://github.com/nijave/borg-windows-package/releases/download/latest/install.ps1

https://github.com/nijave/borg-windows-package/commit/60d464f4d2b3c32889e582d1a558eeeefe30ad2d

**Comment by khakhilev** [comment]
Fixed both 1 & 2
